
model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  trust_remote_code: true
data:
  train:
    datasets:
      - dataset_name: "salary_data.csv"
        split: "train"
training:
  output_dir: "output/salary_model"
  num_train_epochs: 2
  per_device_train_batch_size: 1
  optimizer: "adamw_torch"
  learning_rate: 2e-4
