data:
  train:
    datasets:
    - dataset_kwargs:
        data_files:
        - /Users/devrangoonwala/Desktop/career-compass/salary_data.txt
      dataset_name: text
      dataset_path: /Users/devrangoonwala/Desktop/career-compass/salary_data.txt
      split: train
model:
  model_name: HuggingFaceTB/SmolLM2-135M-Instruct
  trust_remote_code: true
training:
  dataloader_num_workers: 0
  learning_rate: 0.0002
  num_train_epochs: 3
  optimizer: adamw_torch
  output_dir: output/salary_model
  per_device_train_batch_size: 1
  save_steps: 5
